#pragma once

#define IDD_AIASSISTANT_PANEL 8100
#define IDC_AI_CHAT_HISTORY (IDD_AIASSISTANT_PANEL + 1)
#define IDC_AI_INPUT_EDIT (IDD_AIASSISTANT_PANEL + 2)
#define IDC_AI_SEND_BUTTON (IDD_AIASSISTANT_PANEL + 3)
#define IDC_AI_PROVIDER_COMBO (IDD_AIASSISTANT_PANEL + 4)
#define IDC_AI_CLEAR_BUTTON (IDD_AIASSISTANT_PANEL + 5)
#define IDC_AI_SETTINGS_BUTTON (IDD_AIASSISTANT_PANEL + 6)
#define IDC_AI_COPILOT_SIGNIN_BUTTON (IDD_AIASSISTANT_PANEL + 7)
#define IDC_AI_COPILOT_STATUS_STATIC (IDD_AIASSISTANT_PANEL + 8)
#define IDC_AI_FONT_INCREASE_BUTTON (IDD_AIASSISTANT_PANEL + 9)
#define IDC_AI_FONT_DECREASE_BUTTON (IDD_AIASSISTANT_PANEL + 10)
#define IDC_AI_MODEL_COMBO (IDD_AIASSISTANT_PANEL + 11)

#define IDD_AIASSISTANT_SETTINGS 30100
#define IDC_OPENAI_KEY_EDIT 30101
#define IDC_GEMINI_KEY_EDIT 30102
#define IDC_CLAUDE_KEY_EDIT 30103
#define IDC_COPILOT_KEY_EDIT 30104
#define IDC_DEFAULT_PROVIDER_COMBO 30105
#define IDC_TEST_CONNECTION_BTN 30106
#define IDC_SEND_SHORTCUT_CHECK 30107
#define IDC_UI_LANGUAGE_LABEL 30108
#define IDC_UI_LANGUAGE_COMBO 30109
#define IDC_OPENAI_KEY_LABEL 30110
#define IDC_GEMINI_KEY_LABEL 30111
#define IDC_CLAUDE_KEY_LABEL 30112
#define IDC_DEFAULT_PROVIDER_GROUP 30113
#define IDC_DEFAULT_PROVIDER_LABEL 30114
#define IDC_API_KEYS_GROUP 30115
#define IDC_API_KEYS_OPENAI_HINT 30116
#define IDC_API_KEYS_GEMINI_HINT 30117
#define IDC_API_KEYS_CLAUDE_HINT 30118
#define IDC_PROMPT_PROFILE_GROUP 30119
#define IDC_PROMPT_PRESET_LABEL 30120
#define IDC_PROMPT_PRESET_COMBO 30121
#define IDC_RESPONSE_LANGUAGE_LABEL 30122
#define IDC_RESPONSE_LANGUAGE_COMBO 30123
#define IDC_ENCODING_LABEL 30124
#define IDC_ENCODING_COMBO 30125
#define IDC_DETAIL_LEVEL_LABEL 30126
#define IDC_DETAIL_LEVEL_COMBO 30127
#define IDC_SCENARIO_GROUP 30128
#define IDC_SCENARIO_EXPLAIN_CHECK 30129
#define IDC_SCENARIO_FIX_CHECK 30130
#define IDC_SCENARIO_REFACTOR_CHECK 30131
#define IDC_SCENARIO_TEST_CHECK 30132
#define IDC_SCENARIO_DOC_CHECK 30133
#define IDC_OUTPUT_GROUP 30134
#define IDC_OUTPUT_CODE_ONLY_CHECK 30135
#define IDC_OUTPUT_PRESERVE_STYLE_CHECK 30136
#define IDC_OUTPUT_RISKS_CHECK 30137
#define IDC_CUSTOM_PROMPT_GROUP 30138
#define IDC_CUSTOM_PROMPT_EDIT 30139


